### ISSUE TITLE
Concat variables

### ISSUE THREAD

**Issue by derencel20** [mrsteele/dotenv-webpack#135]
`var1=http://www.facebook.com/`
`var2=var1+profile`

is this supported or the syntax above is wrong?

**Comment by mrsteele** [comment]
Hey @derencel20 that would be convered with this: https://github.com/mrsteele/dotenv-webpack/pull/116

The problem is we need a pr on there to be pulled first from the other repo first: https://github.com/motdotla/dotenv-expand/pull/16

**Comment by mrsteele** [comment]
Hey @derencel20, just wanted to mention that since this feature doesn't seem like it was being supported over there, I just added it over here as a configuration option. You should see this option in the latest version of the package.

Because of this, I am closing this issue, let me know if this doesn't directly solve your problem and I'll bring it back up.
