### ISSUE TITLE
Accessing Variables dynamically

### ISSUE THREAD

**Issue by BrandonMurnane** [mrsteele/dotenv-webpack#139]
im trying to either make read-env package work or to access a variable by process.env[var1+'_loginUrl']

**Comment by mrsteele** [comment]
The latter should work if it defined in your `.env` file and you have it configured correctly. You might have to give me a little more information on the issue you are facing for me to help more.

**Comment by BrandonMurnane** [comment]
so i have in my env file LEMON_PASSWORD=grape. but in my app.jsx i cant do 
var name = "LEMON" ;
var password = process.env[name+"_PASSWORD"];
im trying to access them dynamically

**Comment by mrsteele** [comment]
Ahhhh, I see. Yeah I don't think that would work

We look exclusively for the named variables. We do this so that we do not accidentally expose all variables to the user.

You can read more about it here: https://github.com/mrsteele/dotenv-webpack/issues/70#issuecomment-316720414

Since this is sort of related to that comment, I'm going to close for now as it falls in as a duplicate, but I appreciate you bringing this to my attention.
