### ISSUE TITLE
Allow object destructure

### ISSUE THREAD

**Issue by piranna** [mrsteele/dotenv-webpack#142]
https://github.com/mrsteele/dotenv-webpack/blob/2c6abff7492ce039cef74443beff1d11682148f2/src/index.js#L57-L60

`dotenv-webpack` is replacing the references to `process.env` at source code level, just doing a text replace. I use to do object destructure of `process.env` like `const {foo} = process.env`, so this is not changed and I end with `process.env` strings in the browser code.

As a quick solution it would be just enough to add a new replace for `process.env` to the content of `JSON.stringify(vars)`. I know this probably will increase a lot the browser source code and also expose the secrets, so maybe this would need to be under an `unsafe` flag, but better than that would be instead to do a replacement of the exported constants at AST level, although this is more dificult than a simple text replacement.

**Comment by mrsteele** [comment]
This had been reviewed extensively here: https://github.com/mrsteele/dotenv-webpack/issues/70#issuecomment-316720414

The risk of security is far too important to move forward with this approach.

If you do not personally mind for your personal project, feel free to just load in all your env variables.

```js
// webpack.config.js

// have not tested, but probably would look something like this:
const { parsed } = require('dotenv').config()

module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      'process.env': parsed
    })
  ]
}
```

Since we have already covered this extensively in the other thread, I'm going to close this, but feel free to reopen if this is not the case.

**Comment by piranna** [comment]
Yes, I know this first approach has some serious security issues, as I pointed out the best one would be to work at AST level so it would be possible to do the replacements of the variables. Anyway, thanks for pointing out the example code, for some use cases it would be useful :-)
