### ISSUE TITLE
Issue when combined with ESLint

### ISSUE THREAD

**Issue by jessevdp** [mrsteele/dotenv-webpack#171]
I have a Webpack configuration setup where I pull my JS files through ESLint before bundeling them. When I try to set up `dotenv-webpack` and use a random env variable like `process.env.APP_NAME`, ESLint complains about the variable `process` not being defined—which is to be expected.

I removed the `enforce: 'pre'` setting from the ESLint rule, however it seems like ESLint is still run before `dotenv-webpack` is.

Since there is no loader available for `dotenv-webpack` I can not configure it to run before any of my other rules.

**Comment by jessevdp** [comment]
Note that you can fix this problem this by adding `process` to the list of global variables for ESLint (read their [docs](https://eslint.org/docs/user-guide/configuring#specifying-globals) to learn how to do that). But this is not the cleanest way to solve this issue, in my opinion.

**Comment by mrsteele** [comment]
In your eslintrc file, just fix the definition.

```
{
    "env": {
        "node": true // you need this
    }
```

**Comment by jessevdp** [comment]
But that would not be true. The environment for my app is definitely the browser. I need browser API's etc. Setting it to `node` would likely cause a whole list of other problems.

**Comment by mrsteele** [comment]
If that’s the case, I see nothing wrong with the solution recommended by @jessevdp.

Linting for the browser, but in node and before things are transpiled and bundled puts us in this funky place of “the upside-down” (stranger things ref). Our code technically doesn’t run on its own until it has been compiled for use in the browser.

Because of this, making exceptions is the way to go. You need to let your linter know what you have installed and what will work when it does compile, so the exception approach is fine.

I’m closing this for know, but feel free to respond if you have other questions or comments.

**Comment by jessevdp** [comment]
Is there no way to run the "replacement" of `process.env.VAR` syntax before the code hits the linter and other tooling?

With the plugin it seems to be doing this after all of the other loaders are run.

That would, in my opinion, be the best solution. Because that way you are technically just putting strings everywhere.

**Comment by mrsteele** [comment]
I think you are confused (or maybe I am...).

The “loaders” simply define what how to load files. They never run until webpack is called explicitly. So the linting operation doesn’t take place in tandem with webpack, but simply as a code style guide while in development of the source files.

This is a plugin (not a loader), and it is responsible for telling webpack that when it runs it should replace your env variables that exist inline with the contents of those variables (since your bundles are most-likely not going to have scope on your environment).

I don’t think you are correct in your statement above. Your loaders are not running above before linting, the linter is just configured to understand the loading syntax, and in this case needs to be informed that your source files have scope on your process variable at compilation-time.

**Comment by jessevdp** [comment]
Oh shit. I forgot to mention that I'm not using ESLint as a separate tool, but I'm using the ESLint loader. Just to make sure my JS code is actually correct before I try to bundle it.

Isn't it true that some loaders (for example a sass loader) actually do change the contents of a file? "When you load this file, make sure to replace A with B". That's my understanding of it. 

> I don’t think you are correct in your statement above. Your loaders are not running above before linting, the linter is just configured to understand the loading syntax, and in this case needs to be informed that your source files have scope on your process variable at compilation-time.

The last bit of this actually does make sense to me. It would be an optional solution of I could inform my linter that the `process.env` variable is available. But I don't think you can do that... Currently I have set `process` as a global variable... But that implies that I can access other properties of that object as well, which is not true, and could cause a problem that would not be caught by my linter.

I'm honestly fine with this solution. It works. I'll take it. But it does (probably) expose some problems.
