### ISSUE TITLE
Possible to get Environment Variables into process.env? 

### ISSUE THREAD

**Issue by barnomics** [mrsteele/dotenv-webpack#173]
Maybe I'm missing something super simple, but I can't seem to get this to work.   

Loading variables from .env works great, but when the [variable is set](https://webpack.js.org/guides/environment-variables/) through the script I can't seem to find it. 

**package.json**
```
  "scripts": {
    "webpack:wip": "yarn webpack --env.mode development --watch",
  },
```

**webpack.config.js**
```
console.info(mode); // "development"  👍 
```

somewhere in the app.js 
```
console.info(process.env.mode);  // undefined  👎 
```

**Comment by mrsteele** [comment]
A few things to mention:
1. Are you including the plugin in your config (I imagine "yes" but just wanna double check)?
2. Have you set the `systemvars` property to "true"

Under the hood, the `systemvars` property is used to include existing env variables from your current environment. So if you want to only have the `process.env` variables from your `.env` file, you can leave it as false, otherwise set it to "true".

**Comment by barnomics** [comment]
Yes - The plugin setup looks like so: 

```
        new Dotenv({
          path: PATH_TO_ENV,
          safe: false,
          defaults: true,
          systemvars: true
        }),
```

**Comment by mrsteele** [comment]
If you `console.log(new Dotenv({ ... })` do you have the expected results?
Should be something like...
```
// replace `TEST` with your env and you should have your expected results when you build...
console.log(new Dotenv({ ... }['process.env.TEST'])
```

**Comment by barnomics** [comment]
It's only defined within the module exports in my webpack.config.  

Just to reiterate, I can't seem to access the variables that are passed in via scripts. Maybe it has something to [do with this statement about environmental variables](https://webpack.js.org/guides/environment-variables)

> There is one change that you will have to make to your webpack config. Typically, module.exports points to the configuration object. To use the env variable, you must convert module.exports to a function:


Here's my code: 

package.json
```
 "webpack:wip": "yarn webpack --env.mode development --env.something=candy --watch",
```

webpack.config:
```

console.log(new Dotenv({
          path: PATH_TO_ENV,
          safe: false,
          defaults: true,
          systemvars: true
   }).definitions['process.env.mode']);   // undefined.

// actual webpack code: 
module.exports = ({ mode, presets, something } = { mode: 'production', presets: [], something }) => {
  console.info(mode);  // development
  console.info(something); // candy 

  return webpackMerge(
    { .... } // etc
  )

**Comment by mrsteele** [comment]
From the looks of it, you are not setting a variable in the environment, you are just setting a local variable.

Because of that, I would suggest you pass that into the plugins with `webpack.DefinePlugin`. 

```
plugsin: [
  new webpack.DefinePlugin({
    'process.env.mode': mode
  })
]
```

That is out of the scope of this project to handle local variables but that plugin does things perfectly fine for you.

**Comment by barnomics** [comment]
Awesome thanks, that worked! 

Sorry, I thought all of these variables were referring to the same process.env Object but apparently they are not!

**Comment by mrsteele** [comment]
Happy to help and glad we figured it out.

I'll close this for now but let me know if there is anything else.
