### ISSUE TITLE
process.env variables visible in the browser ?

### ISSUE THREAD

**Issue by karborator** [mrsteele/dotenv-webpack#196]
I'm able to see all variable from my .env file in the min.js , is it possible to prevent that ?
npm:3.10.10
node:6.10.10
"react": "^15.4.0",
"webpack-dev-server": "^1.14.1",
"webpack": "^1.15.0",

![image](https://user-images.githubusercontent.com/5076985/82480978-4851ed00-9add-11ea-87f0-d6f18f40c668.png)

**Comment by suixo-akido** [comment]
Hello @karborator, no it is not possible. When you build your bundle with webpack, you are building a big JS file, that then gets downloaded by your clients when they visit your page, so that their browser can execute this bundle - and your JS code.

Since the code is executed in the user's browser, everything is public, including any "secret" you could want to inject in your bundle. Anybody can go and inspect your bundle, and even if you try to "obfuscate" the secret values, as long as the browser is using it it will be easy to find it.

**Comment by karborator** [comment]
Thanks,
I decided to move the client id and secret to the backened and populate them to the request , 
and I verify my frontend with csrf token
