### ISSUE TITLE
Cannot reproduce bug from v3

### ISSUE THREAD

**Issue by mrsteele** [mrsteele/dotenv-webpack#268]
I added v3 to make it backwards-compatible with webpack 4 and still work on webpack 5.

Unfortunately I cannot reproduce the bug that was expressed in #242 .

I need someone who was getting the bug to try and reproduce the bug. I'm starting to wonder if it wasn't my plugin, but perhaps a dependency that had an issue and the timing was more coincidental.

**Comment by flo-sch** [comment]
Hi @mrsteele, I have not updated all dependencies yet (postponed that since we're soon launching the projects I'm working with)

I just re-tried the migration from v2 -> v3 of `dotenv-webpack` only, this is what happens currently for me after upgrading:

> ERROR in [...] from Terser
> Unexpected token: punc (:)

So that looks more like #239 instead of #242 🤔 

I think I reacted in #242 after reading https://github.com/mrsteele/dotenv-webpack/issues/240#issuecomment-697964690

So unable to reproduce the *original* bug mentioned by @thisVioletHydra sorry

**Comment by mrsteele** [comment]
Thanks for reporting back. I'm trying to keep everything in a stable place but webpack has been pretty active since the release of 5 and since this plugin piggy-backs on DefinePlugin I felt a lot of that.

**Comment by flo-sch** [comment]
I personally don't think this bug is a big deal: v2 works fine with webpack4 for most cases...

I am happy to try webpack5 with dotent-webpack5 and forget about v3, no big deal if that specific version is not supported ;)

**Comment by mrsteele** [comment]
Just to clarify, v3 was aimed at resolving an issue where you reference a variable that isn't set. V4 webpack made sure an empty object existed in process.env. I tried that and it seemed to wipe out everything.

This is problematic as it isn't just a silent "undefined" but a error of "process is undefined".
