### ISSUE TITLE
Comparision with webpack-dotenv-plugin

### ISSUE THREAD

**Issue by timkelty** [mrsteele/dotenv-webpack#47]
I still wasn't totally clear on the function differences between this and https://github.com/nwinch/webpack-dotenv-plugin, so before using either I need to test.

My primary concern was if the entire `process.env` would be exposed in the bundled code.

Please correct me if I'm wrong, but it appears that:
 - your plugin will _only_ expose `process.env` variables that explicitly referenced, so your secure/secret vars are not at risk of being bundled (unless you reference them)
- https://github.com/nwinch/webpack-dotenv-plugin seems to expose all of `process.env` in your resulting bundle, which seems super dangerous

https://github.com/mrsteele/dotenv-webpack#how-secure
Your README does reference the fact that it is "secure" a few times, but I still had to to test to see what was going on :) I think the confusion is conflated by the face that webpack-dotenv-plugin uses dotenv-safe, which prior to investigation I assumed was a mechanism to protect secret vars, but in fact isn't that at all.

Anyway - just putting this issue here for anyone else that might go through the same thoughts.
I may send a PR to the README that might have helped me.

**Comment by mrsteele** [comment]
Hey @timkelty!

So your primary concern was my primary concern as well.

It was brought to my attention that webpack would include your entire `process.env` file with each reference (which I considered not only poor in resources but poor in security).

Because of that I rewrote part of my script to specifically replace only referenced variables in your client script.

So to answer your questions / concerns directly:

1. You are right, my plugin only exposes variables you define in your client scripts.
2. That plugin does expose all variables (and in my opinion seems dangerous).

On top of those changes, my plugin also offers a few additional features:

1. Configurable to use `dotenv-safe` or simply `dotenv`.
2. Include your system vars (needed for things like CI).

I also want to request you do a PR for the commit you made to update my `README.md` file. I like your wording more and would love to include that for others to benefit.

Great questions and thanks for the recommendation!

**Comment by timkelty** [comment]
@mrsteele thanks for clearing that up!
PR on its way!
