### ISSUE TITLE
Variable undefined

### ISSUE THREAD

**Issue by TheoMer** [mrsteele/dotenv-webpack#56]
OS: Windows 10 Pro
dotenv-webpack: 1.4.5
webpack: 1.14.0

So I define my webpack as follows:

```
  plugins: [
    new Dotenv({
      path: './.env',
      safe: true
    }),
  ]
```

my .env as follows:

```
// Sentry definitions
Sentry_Key=2342342342342m24242342m2342m24
Sentry_App=23423

// Apollo project id
Apollo_ID=djty23132k23223k232323l331
```

and my .env.example as follows:

```
// Sentry definitions
Sentry_Key=
Sentry_App=

// Apollo project id
Apollo_ID=
```

If I call console.log(process.env.Sentry_Key) and console.log(process.env.Sentry_App), the values are displayed successfully. But console.log(process.env.Apollo_ID) displays `undefined`. 

No matter what variables I define after Sentry_Key and Sentry_App, they all display `undefined`. In fact I even changed the order of the variables around, and still only Sentry_Key and Sentry_App are displayed successfully.

What is the issue here?

**Comment by TheoMer** [comment]
So, replacing `//` with `#`, in both .env and .env.example files, resolved the issue.

Is this a bug?

**Comment by mrsteele** [comment]
This plugin piggy-backs on the parse command in dotenv: https://github.com/mrsteele/dotenv-webpack/blob/master/src/index.js#L71. Because of this I imagine that `//` is not a valid comment for a `.env` file.

I imagine it is something on this line in `dotenv`: https://github.com/motdotla/dotenv/blob/master/lib/main.js#L16

I'm going to close this for now as I don't think this is a bug but simply a syntax issue.
