### ISSUE TITLE
Add option to watch the env file

### ISSUE THREAD

**Issue by denizdogan** [mrsteele/dotenv-webpack#95]
It would be nice if Webpack automatically recompiled my application when changes are detected to my env file. Maybe a simple boolean option named `watch` would suffice? If possible, use chokidar, otherwise fs.

**Comment by mrsteele** [comment]
@denizdogan this is all very dependent on your build system.

If you are using vanilla webpack you can use the `watch` configuration: https://webpack.js.org/configuration/watch/#watch.

Otherwise, I have had success with things like `nodemon` and `onchange` which watch for changes in the filesystem.

I'm closing this as the request is out of scope with the plugin but feel free to reopen if you desire.
